info:
  contact: {}
  title: Example API
paths:
  /:
    get:
      responses: {}
      summary: Hello
      x-perfcheck:
        errorRate:
        - avg_stat < 0.1
        latency:
        - avg < 50
        - min < 50
        - avg_stat < 50
swagger: "2.0"
x-perfcheck:
  stages:
  - duration: 1s
    target: 5
