info:
  contact: {}
  title: Example API
paths:
  /:
    get:
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      responses: {}
      summary: Hello
      x-perfcheck:
        errorRate:
        - avg_stat < 0.1
        latency:
        - avg < 100
        - avg_stat < 100
        responseSize:
        - avg_stat < 20
swagger: "2.0"
x-perfcheck:
  duration: 3
  users: 20
