on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/866888214894/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github@linen-tempest-380208.iam.gserviceaccount.com'

      - name: Deploy new revision
        id: deploy    
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'perfcheck-example'
          source: '.'
          tag: test

      - name: 'Use output'
        run: 'echo "${{ steps.deploy.outputs.url }}"'